# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e4efc8fd785edfabdde526f3e72812437f03576e50e3fb382f4e3c54b8cf0e66d796fb66592e51b363b23e730245b24a34a7e1e050ccdd2a860585e0cb5f36

test:
  secret_key_base: 6ca3aa61d97cc3bc41ece84efbf93d4fa3994312937b0775ff550f6c68a48eeb3f381bdbb8d73dcaba0b1879d3479f00a0ddcbd6e8e36b12cfe170e3996ab79f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
